# Generated by Django 3.2.2 on 2021-06-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('Topic', models.TextField(null=True)),
                ('Yourmessage', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.TextField(null=True)),
                ('Name', models.TextField(null=True)),
                ('About', models.TextField(null=True)),
                ('Type', models.TextField(null=True)),
                ('Worth', models.TextField(null=True)),
                ('Condition', models.TextField(null=True)),
                ('Team', models.TextField(null=True)),
                ('Hereaboutsarathii', models.TextField(null=True)),
                ('helpyou', models.TextField(null=True)),
                ('Yourrecentcustomers', models.TextField(null=True)),
                ('Address', models.TextField(null=True)),
                ('Service', models.TextField(null=True)),
                ('YourName', models.TextField(null=True)),
                ('Phone', models.TextField(null=True)),
                ('Other', models.TextField(null=True)),
            ],
        ),
    ]
