# Generated by Django 3.2.2 on 2021-06-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appsarathii', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Other',
            new_name='other',
        ),
        migrations.AlterField(
            model_name='contact',
            name='Phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Phone',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
