# Generated by Django 3.2.2 on 2021-06-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appsarathii', '0002_auto_20210603_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='helpyou',
            new_name='Helpyou',
        ),
        migrations.AddField(
            model_name='registration',
            name='Streetnumber',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='Zipcode',
            field=models.TextField(max_length=8, null=True),
        ),
    ]
